#!/bin/sh

TARGET=jiayida-mobile

if [ "$1" == "admin" ]
then
  TARGET=jiayida-admin
fi

SRC=$HOME/code/jiayida-group
TOMCAT_HOME=$HOME/tomcat

echo deploy $TARGET
cd $SRC && git pull && mvn -Dmaven.test.skip=true clean package && $TOMCAT_HOME/bin/shutdown.sh && rm -rf $TOMCAT_HOME/webapps/${TARGET}* && find . -name "${TARGET}.war" -exec cp {} $TOMCAT_HOME/webapps \; && $TOMCAT_HOME/bin/startup.sh && cd $HOME/logs && tail -0f `ls ${TARGET}.* | tail -1`
